package com.example.giuliano.flaquiz;

import android.content.ContentValues;
import android.content.Context;
import android.content.Intent;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.media.MediaPlayer;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    private MediaPlayer mp;
    private EditText et_nome;
    private TextView paises;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setIcon(R.mipmap.ic_launcher);

        mp = MediaPlayer.create(this, R.raw.michael_jackson_black_or_white);
        if (!mp.isPlaying()) {
            mp.start();
            mp.setLooping(true);
        }

        AdminSQLiteOpenHelper sqlite = new AdminSQLiteOpenHelper(this, "db", null, 1);
        SQLiteDatabase db = sqlite.getWritableDatabase();

        db.execSQL("delete from paises");

        cadastrarPaises(db);
        db.close();

    }

    public void jogar(View v) {
        et_nome = (EditText) findViewById(R.id.txt_nome);
        String nome = et_nome.getText().toString();

        if (nome.equals("")) {
            Toast.makeText(this, R.string.preencherNome, Toast.LENGTH_SHORT).show();
            et_nome.requestFocus();

            InputMethodManager imm = (InputMethodManager) getSystemService(this.INPUT_METHOD_SERVICE);
            imm.showSoftInput(et_nome, InputMethodManager.SHOW_IMPLICIT);

        } else {
            Intent intent = new Intent(this, Main2Activity.class);
            intent.putExtra("nome", nome);
            startActivity(intent);
        }
    }

    private void cadastrarPaises(SQLiteDatabase db) {
        ContentValues registro = new ContentValues();

        registro.put("codPais", 1);
        registro.put("pais", "Afeganistão");
        registro.put("path", "afghanistan");
        db.insert("paises", null, registro);
        registro.put("codPais", 2);
        registro.put("pais", "Albânia");
        registro.put("path", "albania");
        db.insert("paises", null, registro);
        registro.put("codPais", 3);
        registro.put("pais", "Argélia");
        registro.put("path", "algeria");
        db.insert("paises", null, registro);
        registro.put("codPais", 4);
        registro.put("pais", "Andorra");
        registro.put("path", "andorra");
        db.insert("paises", null, registro);
        registro.put("codPais", 5);
        registro.put("pais", "Angola");
        registro.put("path", "angola");
        db.insert("paises", null, registro);
        registro.put("codPais", 6);
        registro.put("pais", "Antártica");
        registro.put("path", "antarctica");
        db.insert("paises", null, registro);
        registro.put("codPais", 7);
        registro.put("pais", "Antigua e Barbuda");
        registro.put("path", "antigua_and_barbuda");
        db.insert("paises", null, registro);
        registro.put("codPais", 8);
        registro.put("pais", "Argentina");
        registro.put("path", "argentina");
        db.insert("paises", null, registro);
        registro.put("codPais", 9);
        registro.put("pais", "Armenia");
        registro.put("path", "armenia");
        db.insert("paises", null, registro);
        registro.put("codPais", 10);
        registro.put("pais", "Austrália");
        registro.put("path", "australia");
        db.insert("paises", null, registro);
//        registro.put("codPais", 11);
//        registro.put("pais", "Áustria");
//        registro.put("path", "austria");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 12);
//        registro.put("pais", "Azerbaijão");
//        registro.put("path", "azerbaijan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 13);
//        registro.put("pais", "Bahamas");
//        registro.put("path", "bahamas");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 14);
//        registro.put("pais", "Bahrein");
//        registro.put("path", "bahrain");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 15);
//        registro.put("pais", "Bangladesh");
//        registro.put("path", "bangladesh");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 16);
//        registro.put("pais", "Barbados");
//        registro.put("path", "barbados");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 17);
//        registro.put("pais", "Belarus");
//        registro.put("path", "belarus");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 18);
//        registro.put("pais", "Bélgica");
//        registro.put("path", "belgium");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 19);
//        registro.put("pais", "Belize");
//        registro.put("path", "belize");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 20);
//        registro.put("pais", "Benin");
//        registro.put("path", "benin");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 21);
//        registro.put("pais", "Butão");
//        registro.put("path", "bhutan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 22);
//        registro.put("pais", "Bolívia");
//        registro.put("path", "bolivia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 23);
//        registro.put("pais", "Bósnia e Hezergovina");
//        registro.put("path", "bosnia_and_herzegovina");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 24);
//        registro.put("pais", "Botswana");
//        registro.put("path", "botswana");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 25);
//        registro.put("pais", "Brasil");
//        registro.put("path", "brazil");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 26);
//        registro.put("pais", "Brunei");
//        registro.put("path", "brunei");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 27);
//        registro.put("pais", "Bulgária");
//        registro.put("path", "bulgaria");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 28);
//        registro.put("pais", "Burquina Fasso");
//        registro.put("path", "burkina_faso");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 29);
//        registro.put("pais", "Burundi");
//        registro.put("path", "burundi");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 30);
//        registro.put("pais", "Camboja");
//        registro.put("path", "cambodia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 31);
//        registro.put("pais", "Camarões");
//        registro.put("path", "cameroon");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 32);
//        registro.put("pais", "Canadá");
//        registro.put("path", "canada");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 33);
//        registro.put("pais", "Cabo Verde");
//        registro.put("path", "cape_verde");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 34);
//        registro.put("pais", "República Centro Africana");
//        registro.put("path", "central_african_republic");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 35);
//        registro.put("pais", "Chad");
//        registro.put("path", "chad");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 36);
//        registro.put("pais", "Chile");
//        registro.put("path", "chile");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 37);
//        registro.put("pais", "China");
//        registro.put("path", "china");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 38);
//        registro.put("pais", "Colômbia");
//        registro.put("path", "colombia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 39);
//        registro.put("pais", "Comoros");
//        registro.put("path", "comoros");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 40);
//        registro.put("pais", "Costa Rica");
//        registro.put("path", "costa_rica");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 41);
//        registro.put("pais", "Costa do Marfim");
//        registro.put("path", "cote_d_ivoire");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 42);
//        registro.put("pais", "Croácia");
//        registro.put("path", "croatia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 43);
//        registro.put("pais", "Cuba");
//        registro.put("path", "cuba");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 44);
//        registro.put("pais", "Chipre");
//        registro.put("path", "cyprus");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 45);
//        registro.put("pais", "República Tcheca");
//        registro.put("path", "czech_republic");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 46);
//        registro.put("pais", "República Democrática do Congo");
//        registro.put("path", "democratic_republic_of_the_congo");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 47);
//        registro.put("pais", "Dinamarca");
//        registro.put("path", "denmark");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 48);
//        registro.put("pais", "Djibuti");
//        registro.put("path", "djibouti");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 49);
//        registro.put("pais", "Dominica");
//        registro.put("path", "dominica");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 50);
//        registro.put("pais", "República Dominicana");
//        registro.put("path", "dominican_republic");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 51);
//        registro.put("pais", "Timor Leste");
//        registro.put("path", "east_timor");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 52);
//        registro.put("pais", "Equador");
//        registro.put("path", "ecuador");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 53);
//        registro.put("pais", "Egito");
//        registro.put("path", "egypt");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 54);
//        registro.put("pais", "El Salvador");
//        registro.put("path", "el_salvador");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 55);
//        registro.put("pais", "Inglaterra");
//        registro.put("path", "england");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 56);
//        registro.put("pais", "Guiné Equatorial");
//        registro.put("path", "equatorial_guinea");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 57);
//        registro.put("pais", "Eritreia");
//        registro.put("path", "eritrea");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 58);
//        registro.put("pais", "Estônia");
//        registro.put("path", "estonia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 59);
//        registro.put("pais", "Etiópia");
//        registro.put("path", "ethiopia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 60);
//        registro.put("pais", "Fiji");
//        registro.put("path", "fiji");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 61);
//        registro.put("pais", "Finlândia");
//        registro.put("path", "finland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 62);
//        registro.put("pais", "França");
//        registro.put("path", "france");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 63);
//        registro.put("pais", "Guiana Francesa");
//        registro.put("path", "french_guiana");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 64);
//        registro.put("pais", "Gabão");
//        registro.put("path", "gabon");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 65);
//        registro.put("pais", "Gâmbia");
//        registro.put("path", "gambia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 66);
//        registro.put("pais", "Georgia");
//        registro.put("path", "georgia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 67);
//        registro.put("pais", "Alemanha");
//        registro.put("path", "germany");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 68);
//        registro.put("pais", "Gana");
//        registro.put("path", "ghana");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 69);
//        registro.put("pais", "Grécia");
//        registro.put("path", "greece");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 70);
//        registro.put("pais", "Groelândia");
//        registro.put("path", "greenland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 71);
//        registro.put("pais", "Granada");
//        registro.put("path", "grenada");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 72);
//        registro.put("pais", "Guadaloupe");
//        registro.put("path", "guadeloupe");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 73);
//        registro.put("pais", "Guam");
//        registro.put("path", "guam");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 74);
//        registro.put("pais", "Guatemala");
//        registro.put("path", "guatemala");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 75);
//        registro.put("pais", "Guiné");
//        registro.put("path", "guinea");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 76);
//        registro.put("pais", "Guiné Bissau");
//        registro.put("path", "guinea_bissau");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 77);
//        registro.put("pais", "Guiana");
//        registro.put("path", "guyana");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 78);
//        registro.put("pais", "Haiti");
//        registro.put("path", "haiti");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 79);
//        registro.put("pais", "Honduras");
//        registro.put("path", "honduras");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 80);
//        registro.put("pais", "Hong Kong");
//        registro.put("path", "hong_kong");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 81);
//        registro.put("pais", "Hungria");
//        registro.put("path", "hungary");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 82);
//        registro.put("pais", "Islândia");
//        registro.put("path", "iceland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 83);
//        registro.put("pais", "Índia");
//        registro.put("path", "india");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 84);
//        registro.put("pais", "Indonésia");
//        registro.put("path", "indonesia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 85);
//        registro.put("pais", "Irã");
//        registro.put("path", "iran");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 86);
//        registro.put("pais", "Iraque");
//        registro.put("path", "iraq");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 87);
//        registro.put("pais", "Irlanda");
//        registro.put("path", "ireland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 88);
//        registro.put("pais", "Israel");
//        registro.put("path", "israel");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 89);
//        registro.put("pais", "Itália");
//        registro.put("path", "italy");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 90);
//        registro.put("pais", "Jamaica");
//        registro.put("path", "jamaica");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 91);
//        registro.put("pais", "Japão");
//        registro.put("path", "japan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 92);
//        registro.put("pais", "Jordânia");
//        registro.put("path", "jordan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 93);
//        registro.put("pais", "Kazaquistão");
//        registro.put("path", "kazakhstan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 94);
//        registro.put("pais", "Quênia");
//        registro.put("path", "kenya");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 95);
//        registro.put("pais", "Kiribati");
//        registro.put("path", "kiribati");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 96);
//        registro.put("pais", "Coréia do Norte");
//        registro.put("path", "korea_north");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 97);
//        registro.put("pais", "Coréia do Sul");
//        registro.put("path", "korea_south");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 98);
//        registro.put("pais", "Kosovo");
//        registro.put("path", "kosovo");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 99);
//        registro.put("pais", "Kuwait");
//        registro.put("path", "kuwait");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 100);
//        registro.put("pais", "Quirguistão");
//        registro.put("path", "kyrgyzstan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 101);
//        registro.put("pais", "Laos");
//        registro.put("path", "laos");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 102);
//        registro.put("pais", "Letônia");
//        registro.put("path", "latvia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 103);
//        registro.put("pais", "Líbano");
//        registro.put("path", "lebanon");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 104);
//        registro.put("pais", "Lesoto");
//        registro.put("path", "lesotho");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 105);
//        registro.put("pais", "Libéria");
//        registro.put("path", "liberia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 106);
//        registro.put("pais", "Líbia");
//        registro.put("path", "libya");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 107);
//        registro.put("pais", "Liechtenstein");
//        registro.put("path", "liechtenstein");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 108);
//        registro.put("pais", "Lituânia");
//        registro.put("path", "lithuania");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 109);
//        registro.put("pais", "Luxemburgo");
//        registro.put("path", "luxembourg");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 110);
//        registro.put("pais", "Macao");
//        registro.put("path", "macao");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 111);
//        registro.put("pais", "Macedônia");
//        registro.put("path", "macedonia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 112);
//        registro.put("pais", "Madagascar");
//        registro.put("path", "madagascar");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 113);
//        registro.put("pais", "Malawi");
//        registro.put("path", "malawi");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 114);
//        registro.put("pais", "Malásia");
//        registro.put("path", "malaysia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 115);
//        registro.put("pais", "Maldivas");
//        registro.put("path", "maldives");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 116);
//        registro.put("pais", "Mali");
//        registro.put("path", "mali");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 117);
//        registro.put("pais", "Malta");
//        registro.put("path", "malta");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 118);
//        registro.put("pais", "Ilhas Marshall");
//        registro.put("path", "marshall_islands");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 119);
//        registro.put("pais", "Mauritânia");
//        registro.put("path", "mauritania");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 120);
//        registro.put("pais", "México");
//        registro.put("path", "mexico");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 121);
//        registro.put("pais", "Micronésia");
//        registro.put("path", "micronesia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 122);
//        registro.put("pais", "Moldávia");
//        registro.put("path", "moldova");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 123);
//        registro.put("pais", "Mônaco");
//        registro.put("path", "monaco");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 124);
//        registro.put("pais", "Mongólia");
//        registro.put("path", "mongolia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 125);
//        registro.put("pais", "Monte Negro");
//        registro.put("path", "montenegro");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 126);
//        registro.put("pais", "Marrocos");
//        registro.put("path", "morocco");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 127);
//        registro.put("pais", "Moçambique");
//        registro.put("path", "mozambique");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 128);
//        registro.put("pais", "Myanmar");
//        registro.put("path", "myanmar");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 129);
//        registro.put("pais", "Namíbia");
//        registro.put("path", "namibia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 130);
//        registro.put("pais", "Nauru");
//        registro.put("path", "nauru");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 131);
//        registro.put("pais", "Nepal");
//        registro.put("path", "nepal");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 132);
//        registro.put("pais", "Holanda");
//        registro.put("path", "netherlands");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 133);
//        registro.put("pais", "Nova Caledônia");
//        registro.put("path", "new_caledonia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 134);
//        registro.put("pais", "Nova Zelândia");
//        registro.put("path", "new_zealand");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 135);
//        registro.put("pais", "Nicarágua");
//        registro.put("path", "nicaragua");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 136);
//        registro.put("pais", "Níger");
//        registro.put("path", "niger");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 137);
//        registro.put("pais", "Nigéria");
//        registro.put("path", "nigeria");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 138);
//        registro.put("pais", "Noruega");
//        registro.put("path", "norway");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 139);
//        registro.put("pais", "Omã");
//        registro.put("path", "oman");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 140);
//        registro.put("pais", "Paquistão");
//        registro.put("path", "pakistan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 141);
//        registro.put("pais", "Palau");
//        registro.put("path", "palau");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 142);
//        registro.put("pais", "Palestina");
//        registro.put("path", "palestinian");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 143);
//        registro.put("pais", "Panamá");
//        registro.put("path", "panama");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 144);
//        registro.put("pais", "Papua Nova Guiné");
//        registro.put("path", "papua_new_guinea");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 145);
//        registro.put("pais", "Paraguai");
//        registro.put("path", "paraguay");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 146);
//        registro.put("pais", "Peru");
//        registro.put("path", "peru");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 147);
//        registro.put("pais", "Filipinas");
//        registro.put("path", "philippines");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 148);
//        registro.put("pais", "Polônia");
//        registro.put("path", "poland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 149);
//        registro.put("pais", "Portugal");
//        registro.put("path", "portugal");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 150);
//        registro.put("pais", "Porto Rico");
//        registro.put("path", "puerto_rico");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 151);
//        registro.put("pais", "Qatar");
//        registro.put("path", "qatar");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 152);
//        registro.put("pais", "República da China");
//        registro.put("path", "republic_of_china");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 153);
//        registro.put("pais", "República do Congo");
//        registro.put("path", "republic_of_the_congo");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 154);
//        registro.put("pais", "Romênia");
//        registro.put("path", "romania");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 155);
//        registro.put("pais", "Rússia");
//        registro.put("path", "russia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 156);
//        registro.put("pais", "Ruanda");
//        registro.put("path", "rwanda");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 157);
//        registro.put("pais", "São Cristóvão e Nevis");
//        registro.put("path", "saint_kitts_and_nevis");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 158);
//        registro.put("pais", "Santa Lucia");
//        registro.put("path", "saint_lucia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 159);
//        registro.put("pais", "São Vicente e Granadinas");
//        registro.put("path", "saint_vincent_and_the_grenadines");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 160);
//        registro.put("pais", "Samoa");
//        registro.put("path", "samoa");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 161);
//        registro.put("pais", "San Marino");
//        registro.put("path", "san_marino");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 162);
//        registro.put("pais", "São Tomé e Príncipe");
//        registro.put("path", "sao_tome_and_principe");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 163);
//        registro.put("pais", "Arábia Saudita");
//        registro.put("path", "saudi_arabia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 164);
//        registro.put("pais", "Escócia");
//        registro.put("path", "scotland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 165);
//        registro.put("pais", "Senegal");
//        registro.put("path", "senegal");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 166);
//        registro.put("pais", "Sérvia");
//        registro.put("path", "serbia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 167);
//        registro.put("pais", "Seicheles");
//        registro.put("path", "seychelles");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 168);
//        registro.put("pais", "Serra Leoa");
//        registro.put("path", "sierra_leone");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 169);
//        registro.put("pais", "Singapura");
//        registro.put("path", "singapore");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 170);
//        registro.put("pais", "Eslováquia");
//        registro.put("path", "slovakia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 171);
//        registro.put("pais", "Eslovênia");
//        registro.put("path", "slovenia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 172);
//        registro.put("pais", "Ilhas Salomão");
//        registro.put("path", "solomon_islands");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 173);
//        registro.put("pais", "Somália");
//        registro.put("path", "somalia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 174);
//        registro.put("pais", "África do Sul");
//        registro.put("path", "south_africa");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 175);
//        registro.put("pais", "Sudão do Sul");
//        registro.put("path", "south_sudan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 176);
//        registro.put("pais", "Espanha");
//        registro.put("path", "spain");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 177);
//        registro.put("pais", "Sri Lanka");
//        registro.put("path", "sri_lanka");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 178);
//        registro.put("pais", "Sudão");
//        registro.put("path", "sudan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 179);
//        registro.put("pais", "Suriname");
//        registro.put("path", "suriname");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 180);
//        registro.put("pais", "Suazilândia");
//        registro.put("path", "swaziland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 181);
//        registro.put("pais", "Suécia");
//        registro.put("path", "sweden");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 182);
//        registro.put("pais", "Suíça");
//        registro.put("path", "switzerland");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 183);
//        registro.put("pais", "Síria");
//        registro.put("path", "syria");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 184);
//        registro.put("pais", "Tajiquistão");
//        registro.put("path", "tajikistan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 185);
//        registro.put("pais", "Tanzânia");
//        registro.put("path", "tanzania");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 186);
//        registro.put("pais", "Tailândia");
//        registro.put("path", "thailand");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 187);
//        registro.put("pais", "Togo");
//        registro.put("path", "togo");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 188);
//        registro.put("pais", "Tokelau");
//        registro.put("path", "tokelau");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 189);
//        registro.put("pais", "Tonga");
//        registro.put("path", "tonga");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 190);
//        registro.put("pais", "Trinidad e Tobago");
//        registro.put("path", "trinidad_and_tobago");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 191);
//        registro.put("pais", "Tunísia");
//        registro.put("path", "tunisia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 192);
//        registro.put("pais", "Turquia");
//        registro.put("path", "turkey");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 193);
//        registro.put("pais", "Turcomenistão");
//        registro.put("path", "turkmenistan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 194);
//        registro.put("pais", "Tuvalu");
//        registro.put("path", "tuvalu");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 195);
//        registro.put("pais", "Uganda");
//        registro.put("path", "uganda");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 196);
//        registro.put("pais", "Ucrânia");
//        registro.put("path", "ukraine");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 197);
//        registro.put("pais", "Emirados Árabes Unidos");
//        registro.put("path", "united_arab_emirates");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 198);
//        registro.put("pais", "Reino Unido");
//        registro.put("path", "united_kingdom");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 199);
//        registro.put("pais", "Estados Unidos");
//        registro.put("path", "united_states_of_america");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 200);
//        registro.put("pais", "Uruguai");
//        registro.put("path", "uruguay");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 201);
//        registro.put("pais", "Uzbequistão");
//        registro.put("path", "uzbekistan");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 202);
//        registro.put("pais", "Vanuatu");
//        registro.put("path", "vanuatu");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 203);
//        registro.put("pais", "Vaticano");
//        registro.put("path", "vatican_city");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 204);
//        registro.put("pais", "Venezuela");
//        registro.put("path", "venezuela");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 205);
//        registro.put("pais", "Vietnã");
//        registro.put("path", "vietnam");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 206);
//        registro.put("pais", "País de Gales");
//        registro.put("path", "wales");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 207);
//        registro.put("pais", "Saara Ocidental");
//        registro.put("path", "western_sahara");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 208);
//        registro.put("pais", "Iémen");
//        registro.put("path", "yemen");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 209);
//        registro.put("pais", "Zâmbia");
//        registro.put("path", "zambia");
//        db.insert("paises", null, registro);
//        registro.put("codPais", 210);
//        registro.put("pais", "Zimbábue");
//        registro.put("path", "zimbabwe");
//        db.insert("paises", null, registro);

    }

    public static int getResourceId(Context context, String nome, String pasta, String pacote) throws RuntimeException {
        try {
            return context.getResources().getIdentifier(nome, pasta, pacote);
        } catch (Exception e) {
            throw new RuntimeException("Error getting resource ID.", e);
        }
    }

}
